export enum ErrorCode {
  REGISTRATION_FAILED = 'REGISTRATION_FAILED',
  CREDENTIAL_TAKEN = 'CREDENTIAL_TAKEN',
  OLD_PASSWORD_MISMATCH = 'OLD_PASSWORD_MISMATCH',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  REFRESH_TOKEN_MISMATCH = 'REFRESH_TOKEN_MISS_MATCH',
  // Add more error codes as needed
}
